# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- name: Setup eg-customer environment
  hosts: "{{host_inventory}}"
  vars_files:
    - vars/global.yml
    - vars/dn-kafka.yml
  roles:
    - role: dn-kafka/common-roles/ensure-interfaces-up
    - role: dn-kafka/common-roles/get-iface-addr
      iface_name: "{{kafka_iface}}"
    - role: dn-kafka/common-roles/setup-web-proxy
    - role: dn-kafka/common-roles/install-packages
      package_list: "{{kafka_package_list}}"
    - role: dn-kafka
      kafka_addr: "{{iface_addr}}"
